Endless-platforms
renaissance-team/Popolo-grasso pull request #17
Opened 2022-04-22 07:58 UTC by MelnikovAleksei

2022-04-22 12:47 UTC, mvodyanov commented
Называй, пожалуйста, ветки\коммиты с указанием задачи, которые они решают, т.е. 57/endless-platform

2022-04-23 06:50 UTC, VnGrigoreva approved these changes

2022-04-23 13:54 UTC, kxnkxv approved these changes

2022-04-23 13:57 UTC, mvodyanov requested changes

2022-04-24 17:17 UTC, MelnikovAleksei commented on index.html
> +  <div id="root"></div>
@mvodyanov 

я так понимаю что `main` для главной части содержимого страницы, но главная часть не всегда содержит в себе `<header>` / `nav` / `footer` и т.д.

т.е. для корневого элемента `div` все таки подходит больше и можно сделать так:

```
<div id="root">
  <header>
    
  </header>
  <main>
    
  </main>
  <footer>
    
  </footer>
</div>
```

а не так

```
<main id="root">
  <header>
    
  </header>
  <main>
    
  </main>
  <footer>
    
  </footer>
</main>
```

2022-04-24 17:23 UTC, MelnikovAleksei commented on src/components/Game/Game.tsx
> +const PLAYER_WIDTH = 100;
@mvodyanov да

2022-04-24 17:26 UTC, merged